# Generated by Django 5.1.5 on 2025-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_field', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=50)),
                ('company_linkedin', models.URLField(blank=True, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contact_person_phone', models.CharField(max_length=20)),
                ('reason_for_applying', models.TextField()),
            ],
        ),
    ]
